---
- hosts: all
  sudo: yes
  tasks:
    - name: Setup Tsinghua mirror as source
      copy: src=ansible/sources.list dest=/etc/apt/sources.list force=yes
      register: mirror
    - apt: update_cache=yes
      when: mirror.changed
    - include: ansible/install_hadoop.yaml
    - include: ansible/install_spark.yaml
    - include: ansible/install_opencv.yaml
  vars:
    - hadoop_version: 2.6.0
    - apache_mirror: http://mirrors.tuna.tsinghua.edu.cn/apache/
    - spark_version: 1.5.1-bin-hadoop2.6
