export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export HADOOP_INSTALL=/usr/local/hadoop
export PATH="$PATH:$HADOOP_INSTALL/bin:$HADOOP_INSTALL/sbin"
export HADOOP_MAPRED_HOME="$HADOOP_INSTALL"
export HADOOP_COMMON_HOME="$HADOOP_INSTALL"
export HADOOP_HDFS_HOME="$HADOOP_INSTALL"
export YARN_HOME="$HADOOP_INSTALL"
export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_INSTALL/lib/native
